In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('../')
sys.argv=[''] 
del sys

In [3]:
cd "/root/SymmNeRF/"

/root/SymmNeRF


In [5]:
import torch 
W = 128
H = 128

i, j = torch.meshgrid(torch.linspace(0, W - 1, W),
                          torch.linspace(0, H - 1, H))
i = i.t()
j = j.t()

In [9]:
print(f'Shape of i and j: {i.shape}')

Shape of i and j: torch.Size([128, 128])


In [12]:
print(f'First ten row and columns of j: \n\n{j[:10,:10]}')

First ten row and columns of j: 

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])


In [14]:
print(f'First ten row and columns of i: \n\n{i[:10,:10]}')

First ten row and columns of i: 

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [20]:
import numpy as np 

focal = 131.25
cx,cy = 64,64
all_imgs = [i for i in range(100)]

K = np.array([[focal, 0., cx, 0.],
                      [0., focal, cy, 0],
                      [0., 0, 1, 0],
                      [0, 0, 0, 1]]).astype(np.float32)
intrinsics = torch.from_numpy(K)

In [21]:
dirs = torch.stack([(i - K[0][2]) / K[0][0],
                        -(j - K[1][2]) / K[1][1],
                        -torch.ones_like(i)], -1)

In [27]:
print(dirs[10:20,10:20,:])

tensor([[[-0.4114,  0.4114, -1.0000],
         [-0.4038,  0.4114, -1.0000],
         [-0.3962,  0.4114, -1.0000],
         [-0.3886,  0.4114, -1.0000],
         [-0.3810,  0.4114, -1.0000],
         [-0.3733,  0.4114, -1.0000],
         [-0.3657,  0.4114, -1.0000],
         [-0.3581,  0.4114, -1.0000],
         [-0.3505,  0.4114, -1.0000],
         [-0.3429,  0.4114, -1.0000]],

        [[-0.4114,  0.4038, -1.0000],
         [-0.4038,  0.4038, -1.0000],
         [-0.3962,  0.4038, -1.0000],
         [-0.3886,  0.4038, -1.0000],
         [-0.3810,  0.4038, -1.0000],
         [-0.3733,  0.4038, -1.0000],
         [-0.3657,  0.4038, -1.0000],
         [-0.3581,  0.4038, -1.0000],
         [-0.3505,  0.4038, -1.0000],
         [-0.3429,  0.4038, -1.0000]],

        [[-0.4114,  0.3962, -1.0000],
         [-0.4038,  0.3962, -1.0000],
         [-0.3962,  0.3962, -1.0000],
         [-0.3886,  0.3962, -1.0000],
         [-0.3810,  0.3962, -1.0000],
         [-0.3733,  0.3962, -1.0000],
        