In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('../')
sys.argv=[''] 
del sys

In [5]:
cd '/root/SymmNeRF-baseline/code/'

/root/SymmNeRF-baseline/code


In [41]:
from utils.general import compute_cosine_simmilarity
import torch 
import torch.nn as nn 

f1 = torch.rand([1,1,10])
f2 = torch.rand([1,1,10])

print(f'Original f1 tensor: {f1}')
print(f'Original f2 tensor: {f2}')

def compute_cosine_simmilarity_test(f,f_s,G):

    bs = f.shape[0]
    nb_points = f.shape[1]
    ch_size = f.shape[-1]
    local_cs_ch = int(ch_size / G)
    f_split = torch.reshape(f,(bs,nb_points,G,local_cs_ch))
    fs_split = torch.reshape(f_s,(bs,nb_points,G,local_cs_ch))
    
    print(f'Tensor f_split: {f_split} with shape: {f_split.shape}')
    print(f'Tensor fs_split: {fs_split} with shape: {fs_split.shape}')
    
    cosine_simmilarity = nn.CosineSimilarity(dim=-1, eps=1e-08)
    cs = cosine_simmilarity(f_split,fs_split)
    
    return cs 

cs = compute_cosine_simmilarity_test(f1,f2,G=2)

cosine_simmilarity = nn.CosineSimilarity(dim=-1, eps=1e-08)

cs1 = cosine_simmilarity(f1[:,:,:5],f2[:,:,:5])
cs2 = cosine_simmilarity(f1[:,:,5:],f2[:,:,5:])

print(f1[:,:,:5],f2[:,:,:5])
print(cs1,cs2)
print(cs)

Original f1 tensor: tensor([[[0.7804, 0.4787, 0.3530, 0.7954, 0.0462, 0.4543, 0.4527, 0.3520,
          0.7821, 0.0903]]])
Original f2 tensor: tensor([[[0.3504, 0.0338, 0.3736, 0.6599, 0.2324, 0.6651, 0.3398, 0.1097,
          0.4641, 0.9553]]])
Tensor f_split: tensor([[[[0.7804, 0.4787, 0.3530, 0.7954, 0.0462],
          [0.4543, 0.4527, 0.3520, 0.7821, 0.0903]]]]) with shape: torch.Size([1, 1, 2, 5])
Tensor fs_split: tensor([[[[0.3504, 0.0338, 0.3736, 0.6599, 0.2324],
          [0.6651, 0.3398, 0.1097, 0.4641, 0.9553]]]]) with shape: torch.Size([1, 1, 2, 5])
tensor([[[0.7804, 0.4787, 0.3530, 0.7954, 0.0462]]]) tensor([[[0.3504, 0.0338, 0.3736, 0.6599, 0.2324]]])
tensor([[0.8727]]) tensor([[0.6739]])
tensor([[[0.8727, 0.6739]]])


In [36]:
cosine_simmilarity = nn.CosineSimilarity(dim=-1, eps=1e-08)

cs1 = cosine_simmilarity(f1[:,:,:5],f2[:,:,:5])
cs2 = cosine_simmilarity(f1[:,:,5:],f2[:,:,5:])
print(cs1,cs2)
print(cs)

tensor([[0.8634]]) tensor([[0.6676]])
tensor([[[0.8249, 0.7993]]])
